lib/third_rail_web/router.ex
defmodule ThirdRailWeb.Router do
  use ThirdRailWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ThirdRailWeb do
    pipe_through :browser

    get "/", IssueController, :index

    resources "/issues", IssueController do
      resources "/comments", CommentController, only: [:create, :index]
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", ThirdRailWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: ThirdRailWeb.Telemetry
    end
  end
end

lib/third_rail/core/issue.ex
defmodule ThirdRail.Core.Issue do
  use Ecto.Schema
  import Ecto.Changeset

  schema "issues" do
    field :content, :binary
    field :title, :string
    has_many :comments, ThirdRail.Core.Comment, on_delete: :delete_all

    timestamps()
  end

  @doc false
  def changeset(issue, attrs) do
    issue
    |> cast(attrs, [:title, :content])
    |> validate_required([:title, :content])
  end
end

lib/third_rail_web/controllers/issue_controller.ex
defmodule ThirdRailWeb.IssueController do
  use ThirdRailWeb, :controller

  alias ThirdRail.Core
  alias ThirdRail.Core.Issue
  alias ThirdRail.Core.Comment

  def index(conn, _params) do
    issues = Core.list_issues()
    render(conn, "index.html", issues: issues)
  end

  def new(conn, _params) do
    changeset = Core.change_issue(%Issue{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"issue" => issue_params}) do
    case Core.create_issue(issue_params) do
      {:ok, issue} ->
        conn
        |> put_flash(:info, "Issue created successfully.")
        |> redirect(to: Routes.issue_path(conn, :show, issue))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    issue = Core.get_issue!(id)
    comment_changeset = Core.change_comment(%Comment{})
    render(conn, "show.html", issue: issue, comment_changeset: comment_changeset)
  end

  def edit(conn, %{"id" => id}) do
    issue = Core.get_issue!(id)
    changeset = Core.change_issue(issue)
    render(conn, "edit.html", issue: issue, changeset: changeset)
  end

  def update(conn, %{"id" => id, "issue" => issue_params}) do
    issue = Core.get_issue!(id)

    case Core.update_issue(issue, issue_params) do
      {:ok, issue} ->
        conn
        |> put_flash(:info, "Issue updated successfully.")
        |> redirect(to: Routes.issue_path(conn, :show, issue))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", issue: issue, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    issue = Core.get_issue!(id)
    {:ok, _issue} = Core.delete_issue(issue)

    conn
    |> put_flash(:info, "Issue deleted successfully.")
    |> redirect(to: Routes.issue_path(conn, :index))
  end
end

lib/third_rail_web/views/issue_view.ex
defmodule ThirdRailWeb.IssueView do
  use ThirdRailWeb, :view
end

lib/third_rail_web/templates/issue/edit.html.eex
<h1>Edit Issue</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.issue_path(@conn, :update, @issue)) %>

<span><%= link "Back", to: Routes.issue_path(@conn, :index) %></span>

lib/third_rail_web/templates/issue/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :title %>
  <%= text_input f, :title %>
  <%= error_tag f, :title %>

  <%= label f, :content %>
  <%= text_input f, :content %>
  <%= error_tag f, :content %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/third_rail_web/templates/issue/index.html.eex
<h1>Listing Issues</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for issue <- @issues do %>
    <tr>
      <td><%= issue.title %></td>
      <td><%= issue.content %></td>

      <td>
        <span><%= link "Show", to: Routes.issue_path(@conn, :show, issue) %></span>
        <span><%= link "Edit", to: Routes.issue_path(@conn, :edit, issue) %></span>
        <span><%= link "Delete", to: Routes.issue_path(@conn, :delete, issue), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Issue", to: Routes.issue_path(@conn, :new) %></span>

lib/third_rail_web/templates/issue/new.html.eex
<h1>New Issue</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.issue_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.issue_path(@conn, :index) %></span>

lib/third_rail_web/templates/issue/show.html.eex
<h1 id="issue" data-issue-id="<%= @issue.id %>">Show Issue</h1>

<ul>

  <li>
    <strong>Title:</strong>
    <%= @issue.title %>
  </li>

  <li>
    <strong>Content:</strong>
    <%= @issue.content %>
  </li>

</ul>

<turbo-frame id="comments" src="<%= Routes.issue_comment_path(@conn, :index, @issue.id) %>">
  <svg class="spinner" width="65px" height="65px" viewBox="0 0 66 66" xmlns="http://www.w3.org/2000/svg">
       <circle class="path" fill="none" stroke-width="6" stroke-linecap="round" cx="33" cy="33" r="30"></circle>
  </svg>
</turbo-frame>

<h3>New Comment</h3>
<turbo-frame id="comment_form">
  <%= form_for @comment_changeset, Routes.issue_comment_path(@conn, :create, @issue.id), fn f -> %>
    <%= text_input f, :content %>
    <%= submit "Comment" %>
  <% end %>
</turbo-frame>

<span><%= link "Edit", to: Routes.issue_path(@conn, :edit, @issue) %></span>
<span><%= link "Back", to: Routes.issue_path(@conn, :index) %></span>